### ISSUE TITLE
Local SVG files are not rendered

### ISSUE THREAD

**Issue by appoll** [TheThingsNetwork/docs#10]
![image](https://cloud.githubusercontent.com/assets/6266466/13285670/221ce824-dafc-11e5-8e27-ae6f9fee262e.png)

As it can be seen above, none of the linked images are displayed.
Did some research and this is a known issue: 
https://github.com/cinder/Cinder/pull/1161
https://github.com/isaacs/github/issues/316

Possible solutions are: 

1. using the [rawgit](https://rawgit.com/) service 
2. "put the SVG files on the gh-pages branch and link to the files from github.io" ([source](http://stackoverflow.com/a/16462143/1368705))

if agreed, i could take the time for it

**Comment by KtorZ** [comment]
I'll review again all those documentation pages in a while (end of March). Some parts deserve an update, and some others are now outdated. 
I don't have time at the moment to tackle those issues and your help is more than appreciated :)

Go ahead if you've got some time, I'll merge :)
