### ISSUE TITLE
Flowchart: Downlink windows

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#112]
Create a graphic to show that:

- Only last scheduled downlink is preserved
- You have limited time to respond to a message

/cc @wesselversluis @laurensslats

**Comment by FokkeZB** [comment]
I think @johanstokking has one pretty good one in his slide deck?

**Comment by johanstokking** [comment]
I don't have any unfortunately. But indeed, this is a handy graph

**Comment by htdvisser** [comment]
![rx-window](https://cloud.githubusercontent.com/assets/181308/21357003/f900c892-c6d3-11e6-91b1-c670cad18f5f.png)

**Comment by htdvisser** [comment]
> @FokkeZB: Only last scheduled downlink is preserved

This will change in the future (https://github.com/TheThingsNetwork/ttn/issues/357)

> @FokkeZB: You have 2 windows of opportunity to respond to deliver a downlink in response to a message you process.

Not true. Only one.

**Comment by FokkeZB** [comment]
Or this one we used in Ulm?

![respond](https://cloud.githubusercontent.com/assets/2699409/21392294/7ebc29b6-c78f-11e6-8853-2c312bf851b6.png)

**Comment by FokkeZB** [comment]
@htdvisser why only 1 opportunity? If you don't make the first window you get another chance the second one right?

**Comment by htdvisser** [comment]
Because the Broker selects a downlink option before it forwards the message to the Handler. Therefore the downlink window has already been decided before a message is sent to the Application. Our Handler currently waits for a response from the application for max. 100ms, regardless of the downlink window.
