### ISSUE TITLE
Guide: The Things Gateway

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#13]

**Comment by FokkeZB** [comment]
Hey @johanstokking could you unassign or reassign this issue? Thx!

**Comment by htdvisser** [comment]
What's the status of this @rish-c @laurensslats @johanstokking? What still needs to be done/improved?

**Comment by htdvisser** [comment]
Some TODOs:

- [ ] Add Activation Video
- [x] Add FAQ (copy/paste from https://www.thethingsnetwork.org/forum/t/ttn-gateway-faq/11173)
- [x] Add meaning of LEDs (import from https://github.com/TheThingsProducts/gateway/blob/master/doc/LEDs.md)
