### ISSUE TITLE
Bytes document, signed values

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/docs#130]
https://github.com/TheThingsNetwork/docs/blob/master/_content/devices/bytes.md#index-round-and-shift

According to me it is not true that your examples all just work for signed values. I might be mistaken though.

In my case I transmit a 2 byte signed integer. On the javascript side 4 bytes are used for an integer. Therefore I need to check the highest order bit of the 2 byte integer, and fill the highest order 16 bits of the value in javascript. Something like this piece of code:
```
  var altValue = ((bytes[0]<<8)>>>0) + bytes[1];
  var sign = bytes[0] & (1 << 7);
  if(sign)
  {
    decoded.alt = 0xFFFF0000 | altValue;
  }
  else
  {
    decoded.alt = altValue;
  }
```
The above code gives me the correct negatie value, while the next piece of code that is listed in the bytes document gives me an incorrect positive value.
```
  decoded.alt = (bytes[0]<<8) + bytes[1];
```

**Comment by johanstokking** [comment]
Yes, true. You can file a PR

I think there's stuff in this file that can be removed too. It's a bit bloated.
