### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by martinbeentjes** [TheThingsNetwork/docs#134]
The building of the master branch by Travis is broken. It gets a 403 error when pushing, see the [build log](https://travis-ci.org/TheThingsNetwork/docs/builds/201489476)

Is this a known issue?

**Comment by johanstokking** [comment]
Resolved by https://github.com/TheThingsNetwork/docs/commit/7d15094cdc7c2c6133127011d8288c6d9f4a938a
