### ISSUE TITLE
Add page with all the videos highlighted section

### ISSUE THREAD

**Issue by wienke** [TheThingsNetwork/docs#145]

**Comment by jpmeijers** [comment]
To summarise what I understand should happen:
* On https://www.thethingsnetwork.org/docs/, under Documents add a tile "About Us".
* Make the tile link to a page with a list of videos about us.

@wienke Is this what you meant?

Perhaps this task is more suited for @gomezjdaniel?

**Comment by johanstokking** [comment]
I think it's the how-to videos embedded, right?

**Comment by laurensslats** [comment]
Embedded the movies in the Docs
