### ISSUE TITLE
Fix edit button 

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/docs#146]
On the website the edit button sometimes doesn't send the user to the correct page

**Comment by johanstokking** [comment]
We should get rid of the edit button

**Comment by htdvisser** [comment]
I disagree. Especially when we move the Wiki contents to the Docs, it shouldn't be too complicated to edit the docs. The Edit button (usually) sends you to the page on Github where you can edit and submit a pull request, which is great. Let's not remove that

**Comment by johanstokking** [comment]
OK, I was thinking of inline editing, but it should be GitHub, so if "edit" is essentially a link then that's perfect.

What's wrong about the link?

**Comment by htdvisser** [comment]
It sometimes didn't send you to the right page. Can't reproduce it right now. Will reopen when I find an example.
