### ISSUE TITLE
Add documentation to operate a factory reset on Multitech Conduit via uboot

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/docs#167]
* Access uboot
* Start a server on your machine on macOS, Windows, Linux
* Start factory reset procedure

**Comment by kersing** [comment]
Doesn't it make sense to point to the relevant pages on multitech.net (http://www.multitech.net/developer/software/mlinux/using-mlinux/flashing-mlinux-firmware-for-conduit/)? Also keep in mind access to uboot on the AP models requires opening the box (warranty issue?) and additional hardware (serial 3V3 to USB or RS232 convertor) making it impractical for 90% of the users requiring instructions. (The other 10% do not need these instructions or are able to find them on the MultiTech website)
