### ISSUE TITLE
How saving device message

### ISSUE THREAD

**Issue by mazareth** [TheThingsNetwork/docs#177]
Hi,

can we have an historic of device's messages?

When i leave the thethingnetwork interface. All messages are lose.
But i want to test my gateway during a week.

Have you an integrated solution?

**Comment by johanstokking** [comment]
@mazareth yes. We have the Storage Integration, see https://www.thethingsnetwork.org/docs/applications/storage/

**Comment by mazareth** [comment]
Thanks.

Thats what i searching for.

**Comment by mazareth** [comment]
Hi,
I've configure the data storage yesterday but this morning i've only the 3 last data saved on my GUI.

![image](https://user-images.githubusercontent.com/19725586/33059830-3be6a184-ce96-11e7-9c50-f312594c3567.png)

When i take the data it's ok
![image](https://user-images.githubusercontent.com/19725586/33059713-c9366e62-ce95-11e7-9294-5e8d8589e2d9.png)
![image](https://user-images.githubusercontent.com/19725586/33059880-83d9b06c-ce96-11e7-9472-e4c16652c5e3.png)

But how can i see them in thethingnetwork GUI?

**Comment by johanstokking** [comment]
@mazareth we don't go back that far in the Console; it's set to 30 minutes. If you need more history, call the API directly.

**Comment by mazareth** [comment]
What do you mean by calling the API?

I've to install curl?
I don't know how to get the data and have a friendly interface.

**Comment by johanstokking** [comment]
Friendly interfaces are provided by many IoT platforms. See the Integrations panel in the Application Overview. You can use Cayenne, AllThingsTalk, EVRYTHNG, etc, all providing visualization and long time data storage. Also, it's easy to build something yourself with Node-RED. We focus specifically on the networking layer.

**Comment by mazareth** [comment]
Thanks again Johan.
I test Cayenne and EVRYTHING. 
Cayenne works and give me what i want. It's easy to use.

I don't understand how EVRYTHING work.
