### ISSUE TITLE
Best Practices section

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/docs#193]
Many hobbyists and to-be LoRaWAN professionals are using our docs as an introduction to device programming, especially those experimenting with Things Unos or Things Nodes.
It would thus be relevant to have a Best Practices section, that could be for example inspired by the LoRaWAN best practices document.

**Comment by johanstokking** [comment]
Blocked till best practices document is released

**Comment by egourlao** [comment]
I've started a Best Practices page here: https://www.thethingsnetwork.org/docs/devices/bestpractices.html, but it's nowhere complete yet.

**Comment by johanstokking** [comment]
Great. Needs indeed elaboration when that document is out
