### ISSUE TITLE
Add guide to contribute to the documentation

### ISSUE THREAD

**Issue by MaartenArits** [TheThingsNetwork/docs#240]
I would like to contribute to the documentation but is don't know how to do this. A reference to the tools used and their getting started guides would be very helpful. I suggest doing this in the Readme.md file or at least point in the right direction

**Comment by johanstokking** [comment]
Great!

What misses exactly from the README? It guides you running everything locally.

The rest is basically the GitHub workflow; fork the repository, make changes (in a new branch), and submit a pull request here.

**Comment by MaartenArits** [comment]
I'm not yet to familiar with the work flow but would love to contribute. I guess is have to start by learning Jekyll? Is there a standard way to order documents, upload images, add JavaScript and so on or does it all become clear once you get started?

**Comment by johanstokking** [comment]
Yes, it's essentially a matter of working under `_content` and following in the instructions in the README.
