### ISSUE TITLE
Next link in the Learning section

### ISSUE THREAD

**Issue by MaartenArits** [TheThingsNetwork/docs#241]
I would be nice to be able to easily navigate to the next topic / section when reading the learning section. Now you have to scroll up al the way.

**Comment by johanstokking** [comment]
There's not really an order in the documentation, I'm afraid. Articles are sorted in the menu on the left, though, but I'm not sure if we can use this. If you find a way to do to this with [Jekyll](https://jekyllrb.com/), please work with us on a solution for this issue.
