### ISSUE TITLE
Clarify 1.4 version for Kerlink

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/docs#258]
Currently, it's not very clear if its better to use 1.3 or 1.4.

Can you explain a bit more about the V1.4? When to use it? What kind of logging? How and where to see the logs? Do I need to remove V1.3 before I can install V1.4?

Maybe it's better to create a new header with **Troubleshooting**?

**Comment by egourlao** [comment]
Done: https://github.com/TheThingsNetwork/docs/commit/b6f415a3796cc40bacdb22a64ea1d85a28c69f6e
