### ISSUE TITLE
ttn.fyi/activate allows for shorter gateway IDs than the gateway web UI

### ISSUE THREAD

**Issue by stapelberg** [TheThingsNetwork/docs#276]
Please move this issue to the appropriate place if I’m filing it in the wrong place, I couldn’t see a “send feedback” link on the website.

I activated my TTN-ND-868 gateway using the id `gw0`. After clearing the WiFi settings by pressing Mode for 2 seconds, I logged into the web UI at 192.168.84.1 and tried to change to a different WiFi network. Unfortunately, the form wouldn’t let me submit anything because it tried to validate that the gateway id is at least 6 characters.

Perhaps the activation should be more strict, or the gateway should be less strict.

Thanks!

**Comment by htdvisser** [comment]
Thanks for reporting. The gateway should indeed be less strict about this. I'll move the issue to the Gateway repository.

**Edit:** Can't move it, I'll reference it in https://github.com/TheThingsProducts/gateway
