### ISSUE TITLE
docs: the things node quick start wrong intervals?

### ISSUE THREAD

**Issue by tdsmtdsm** [TheThingsNetwork/docs#284]
The [quick start doc](https://github.com/TheThingsNetwork/docs/blob/master/_content/devices/node/quick-start.md) for TheThingsNode [mentions](https://www.thethingsnetwork.org/docs/devices/node/quick-start.html#interval) 8 seconds and 8000ms as sleep interval but the Arduino library example code contains 60000 as sleep interval.

**Comment by johanstokking** [comment]
Thanks for reporting.

>but the Arduino library example code contains 60000 as sleep interval.

Can you add a reference?

**Comment by tdsmtdsm** [comment]
The Basic example sketch has 60000 as interval argument: [https://github.com/TheThingsNetwork/arduino-node-lib/blob/master/examples/Basic/Basic.ino#L56](https://github.com/TheThingsNetwork/arduino-node-lib/blob/master/examples/Basic/Basic.ino#L56)

Elsewhere, the quick start doc talks about 20 seconds as interval: [https://github.com/TheThingsNetwork/docs/blob/master/_content/devices/node/quick-start.md#send-data](https://github.com/TheThingsNetwork/docs/blob/master/_content/devices/node/quick-start.md#send-data)

Might be confusing for quick starters.

**Comment by johanstokking** [comment]
The minimum is 8 seconds. Indeed it would be more clear if we choose a multiple of 8.
