### ISSUE TITLE
Integrate with Arduino Create Agent

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#30]
The OSS [Arduino Create Agent](https://github.com/arduino/arduino-create-agent) is what powers the [Arduino Web Editor](https://create.arduino.cc/editor).

It looks like we could push code directly to ones connected node from docs if the user has this helper app installed.

So far though, I run into issues even getting the web editor to work.

**Comment by htdvisser** [comment]
Is this still a thing? @laurensslats @johanstokking have we had any requests for this?

**Comment by johanstokking** [comment]
No demand for this until now.
