### ISSUE TITLE
Add FAQ section?

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#31]
Not sure if docs is the right place, but it would be great to have a searchable page with FAQs like:
- Can I register a device to multiple applications?
- ...

**Comment by htdvisser** [comment]
We used to have this on the wiki, because then the community can contribute answers.

**Comment by FokkeZB** [comment]
That's a better place indeed. I have it on my list to restructure the Wiki this week and I'll add a FAQ section
