### ISSUE TITLE
Guide: Java Library

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#32]
See https://github.com/TheThingsNetwork/java-app-lib/issues/3

**Comment by cambierr** [comment]
I started writing it but troubles with my local setup (style not loaded so it's hard to get a real preview) made me not able to commit/push anything clean. I'll complete it asap

**Comment by FokkeZB** [comment]
Mmm, interesting. It should work if you follow the steps from the readme. What errors did you run in to? Could you create an issue at https://github.com/thethingsNetwork/docs/issues ?

**Comment by cambierr** [comment]
From what I see, there is no error, just a missing main.css file.
I'm running it inside a docker container to avoid installing tons of package on my machine. I'll investigate that later this week and create an issue in case I can't manage to have it working

**Comment by FokkeZB** [comment]
Jekyll should generate that file at `_site/css/main.css` when it generates the site. Let me know.
