### ISSUE TITLE
Mikrotik Config Instructions

### ISSUE THREAD

**Issue by KE6MTO** [TheThingsNetwork/docs#323]
Based on beta 6.46beta44, the LoRa configuration is in the root of the menu, not under IP. Need configuration information for US915 to create sub-band 2 as the beta only has sub-band 1.

**Comment by johanstokking** [comment]
Thanks @KE6MTO, can you submit a PR?

**Comment by carlanwray** [comment]
I'm going to give it a try. They have the move in the current stable release.
