### ISSUE TITLE
Bundler could not find compatible versions for gem "ruby ":

### ISSUE THREAD

**Issue by MarkNambatac** [TheThingsNetwork/docs#330]
When I run the command `bundle install`, this is what i get: 

```
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby ":
  In Gemfile:
    ruby

    jemoji was resolved to 0.9.0, which depends on
      html-pipeline (~> 2.2) was resolved to 2.7.1, which depends on
        nokogiri (>= 1.4) was resolved to 1.8.2, which depends on
          ruby  (< 2.6) x64-mingw32

Could not find gem 'ruby  (< 2.6)', which is required by gem 'nokogiri (>=
1.4)', in any of the relevant sources:
  the local ruby installation
```

I found a solution by running `bundle update`, but this will create an error when I push it in github: 
![image](https://user-images.githubusercontent.com/19337729/67154306-9545c900-f32c-11e9-8b5f-01cba48c54e9.png)

I am using **ruby 2.6.4p104** (2019-08-28 revision 67798)

**Comment by johanstokking** [comment]
@MathieuMonneret can you pick this up as part of dependency updates?

**Comment by MathieuMonneret** [comment]
We updated travis CI configuration to work with latest Bundler version, 
could you try pushing it to git once more and tell us if you experiment the same issue.

**Comment by johanstokking** [comment]
Please reopen if this issue persists.
