### ISSUE TITLE
Quick-Start CLI - Different versioning?

### ISSUE THREAD

**Issue by ZeroSum24** [TheThingsNetwork/docs#385]
Hi all, 

The [CLI quick-start menu](https://www.thethingsnetwork.org/docs/network/cli/quick-start.html) seems to point to an older version of `ttnctl` than the [v3.8.3 documentation](https://thethingsstack.io/v3.8.3/getting-started/) which points to `ttn-lw-cli`. 

Pointing this out to help clear up any confusion in case any other client-devs notice this and in case this is helpful to yourselves at TTN in anyway.

**Comment by KrishnaIyer** [comment]
Thanks @ZeroSum24. The documentation and the links are correct in that they are for our current v2 stack. 

When we deploy the new `v3` stack for community, we'll update that.
