### ISSUE TITLE
Document Basic Station setting for TTN

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/docs#392]
When I Google for "the things network basic station" I have the top result the official TTN docs page for Basic Station:
https://github.com/TheThingsNetwork/docs/edit/master/_content/gateways/packet-forwarder/basicstation.md

This page however does not provide the TTN specific information I am looking for when I set up a gateway.

We should update the docs to be similar to this forum post:
https://www.thethingsnetwork.org/forum/t/setting-up-basic-station-protocol-on-rak7240-and-rak7249-industrial-gateways/37011
And maybe include this:
https://www.thethingsnetwork.org/forum/t/using-lora-basics-station-on-rpi-gateway/33403/8

**Comment by benolayinka** [comment]
Updated here https://www.thethingsnetwork.org/docs/gateways/basics-station/ from https://github.com/TheThingsNetwork/docs/pull/393
