### ISSUE TITLE
Mark docs as V2 only and link to V3 documentation

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/docs#406]
Let's mark this documentation as V2 specific and link to the V3 docs for The Things Stack.

Here:
<img width="1165" alt="Screenshot 2020-11-02 at 15 01 48" src="https://user-images.githubusercontent.com/6963436/97888216-2ff02a80-1d2b-11eb-8744-56e8097703c8.png">

And here:
<img width="989" alt="Screenshot 2020-11-02 at 15 02 05" src="https://user-images.githubusercontent.com/6963436/97888222-34b4de80-1d2b-11eb-8121-87779ceab7c0.png">

**Comment by benolayinka** [comment]
@GreenPenguino have you worked on the TTN docs page? Could you help modify the layout to add this note? We want to put a big note at the top of the TTN documentation that it only applies to V2, and add a link to The Things Stack (v3) documentation.

**Comment by GreenPenguino** [comment]
I have not worked on TTN docs, but willing to try

**Comment by benolayinka** [comment]
Will be closed by https://github.com/TheThingsNetwork/docs/pull/407
