### ISSUE TITLE
Incorrect Type 3 and Type 4 NetId Prefix allocation on prefix-assignments.md

### ISSUE THREAD

**Issue by kalik1** [TheThingsNetwork/docs#408]
Standing to latest  **LoRaWAN NetID Allocations (Revision 3)** and to errata
https://lora-alliance.org/resource-hub/nwkid-length-fix-type-3-and-type-4-netids-errata-lorawan-backend-10-specification, it looks that type 3 address space is **/15** and not ~/14~ as reported in [prefix-assignments.md](https://github.com/TheThingsNetwork/docs/blob/master/_content/lorawan/prefix-assignments.md).

**Comment by johanstokking** [comment]
@kalik1 Yes, that changed. Can you file a pull request?

**Comment by kalik1** [comment]
Done.  (-:
