### ISSUE TITLE
Landing page icons redesign 

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/docs#434]
We need some redesigned icons for the TTN docs landing page. This is what we currently have:

![icons](https://user-images.githubusercontent.com/65215579/111320153-ff1fea80-8666-11eb-8f2d-a84aa4441d70.png)
![icons-connected](https://user-images.githubusercontent.com/65215579/111320162-01824480-8667-11eb-9c72-7e04a024ab4e.png)

I guess we can reuse some icons used for TTS docs page, i.e.:

![tts_icons](https://user-images.githubusercontent.com/65215579/111320435-3e4e3b80-8667-11eb-8953-871587618e2d.png)

@benolayinka @laurensslats any ideas?

**Comment by pierrephz** [comment]
@nejraselimovic find here a schema you can use for the Learn page:

![learn_schema](https://user-images.githubusercontent.com/26456318/112339497-0165f280-8cc0-11eb-9507-a4e360861009.png)

Here is a .zip where you will find icons to replace the outdated ones: [learn_page_icons.zip](https://github.com/TheThingsNetwork/docs/files/6198618/learn_page_icons.zip)

Later this week all the icons we have so far will be available in the design repo

**Comment by pierrephz** [comment]
Quick UI fix:

![image](https://user-images.githubusercontent.com/26456318/112340871-42123b80-8cc1-11eb-9104-73c1f652b498.png)

If you can just put the text on top of the shema (and not beside) it would be cool.
I see this page needs a complete UI rework but I don't know when I will be able to dot it, so until then it could be nice to do this

**Comment by nejraselimovic** [comment]
> Quick UI fix:
> 
> ![image](https://user-images.githubusercontent.com/26456318/112340871-42123b80-8cc1-11eb-9104-73c1f652b498.png)
> 
> If you can just put the text on top of the shema (and not beside) it would be cool.
> I see this page needs a complete UI rework but I don't know when I will be able to dot it, so until then it could be nice to do this

Sure, that should be easy to fix. Great work with the icons!

**Comment by benolayinka** [comment]
Closed by #467
