### ISSUE TITLE
Change the UI of the "What's new" section

### ISSUE THREAD

**Issue by pierrephz** [TheThingsNetwork/docs#456]
#### Summary

Change the UI of the `What's new` section

#### Why do we need this ?

Now, the UI tells the user that he can scroll horizontally. But this is not the case, so we need to fix this

#### What is already there? What do you see now?

![image](https://user-images.githubusercontent.com/26456318/121014106-e290db80-c799-11eb-91cb-f201b435c836.png)

#### What is missing? What do you want to see?

<img width="1440" alt="Group 78" src="https://user-images.githubusercontent.com/26456318/121015323-27694200-c79b-11eb-860d-e5a16738ba2d.png">

Remove this gradient on the right side, add the number of changes that have been made

#### How do you propose to document this?

@benolayinka can you take this up? or let me know how you want to proceed
The mockup is ready, I can give further details to the developer

#### Can you do this yourself and submit a Pull Request?

Need @benolayinka

**Comment by benolayinka** [comment]
dunno if this is worth it but @kschiffer let me know what you think. if you like I can also implement it, you'll just be faster and produce a better result 🤷🏼‍♀️

**Comment by kschiffer** [comment]
I think @pierrephz is giving this a go himself actually. :muscle:
