### ISSUE TITLE
Please add gateway claiming to TTIG instructions page

### ISSUE THREAD

**Issue by kersing** [TheThingsNetwork/docs#460]
#### Summary

The TTIG activation process does not mention or reference the claiming proces required to point the gateway to the right TTS instance.

#### Why do we need this ?

Update is required to prevent confusion for new gateway owners not understanding why their gateway does not show online in the stacks console.

#### What is already there? What do you see now?

Claiming process is documented on the website (if you can find it, documentation get hard to navigate lately)

#### What is missing? What do you want to see?

...

#### How do you propose to document this?

Add the claiming process or a link to the relevant page. (https://www.thethingsnetwork.org/docs/gateways/thethingsindoor/)

#### Can you do this yourself and submit a Pull Request?

...

**Comment by benolayinka** [comment]
Closed by https://github.com/TheThingsNetwork/docs/commit/c10cec3f6a150b45309406ddeda4246cd358625c#diff-317533c51f888812bf446abdc7a76d8635c16db93fc37d96d73482ee305dc852
