### ISSUE TITLE
Message Types page (figure) shows an incorrect field size for the FOpts field.

### ISSUE THREAD

**Issue by pradeeka7** [TheThingsNetwork/docs#468]
#### Summary

In the **Message Types** page (https://www.thethingsnetwork.org/docs/lorawan/message-types/), the figure shows incorrect size for the **FOpts** field. It should be corrected as **0..15 bytes**.

#### Why do we need this ?

...

#### What is already there? What do you see now?

![image](https://user-images.githubusercontent.com/36432168/132445468-0d0f0144-9042-4f4f-b701-3dcaf5fb35d4.png)

#### What is missing? What do you want to see?

![image](https://user-images.githubusercontent.com/36432168/132445605-ad9ea58c-a65b-42b7-b01d-7da411fe1d98.png)

#### How do you propose to document this?

Please edit the image.

#### Can you do this yourself and submit a Pull Request?

...

**Comment by pradeeka7** [comment]
@benolayinka Please look into this.

**Comment by pierrephz** [comment]
[radio-phy-layer.png.zip](https://github.com/TheThingsNetwork/docs/files/7373399/radio-phy-layer.png.zip)
cc @benolayinka

**Comment by pradeeka7** [comment]
> [radio-phy-layer.png.zip](https://github.com/TheThingsNetwork/docs/files/7373399/radio-phy-layer.png.zip) cc @benolayinka

@benolayinka -  I will submit a pull request for this.
