### ISSUE TITLE
Fix "what's new" page styling

### ISSUE THREAD

**Issue by pgalic96** [TheThingsNetwork/docs#474]
#### Summary

The whats new page styling is broken:

<img width="1903" alt="Screenshot 2021-09-28 at 2 23 27 PM" src="https://user-images.githubusercontent.com/19795814/135087679-c41e8202-5544-479e-9bac-9093a576d3ef.png">

#### Why do we need this ?

To fix the styling

#### What is already there? What do you see now?

Broken page

#### What is missing? What do you want to see?

Non-broken page

#### Can you do this yourself and submit a Pull Request?

@benolayinka

**Comment by benolayinka** [comment]
wrong repo. closing for https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/628
