### ISSUE TITLE
Document additional LoRa hardware

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/docs#498]
#### Summary

Once #497 is merged, lets add more common devices from https://www.semtech.com/products/wireless-rf/lora-core and the LR1110 in the same format.

#### Why do we need this ?

Provide additional information on TTN learn

**Comment by nejraselimovic** [comment]
do we have any info on which devices exactly are the common ones?

**Comment by jpmeijers** [comment]
* SX1276, SX1272 - supported by LMiC - https://github.com/mcci-catena/arduino-lmic

* SX1261, SX1262 and SX1268 - supported by https://github.com/beegee-tokyo/SX126x-Arduino

* And then the LR1110.

These are the only ones I've really seen being used. Even the SoCs and modules that can do LoRa are all based on one of the above ones.

**Comment by nejraselimovic** [comment]
> * SX1276, SX1272 - supported by LMiC - https://github.com/mcci-catena/arduino-lmic
> 
>     * SX1261, SX1262 and SX1268 - supported by https://github.com/beegee-tokyo/SX126x-Arduino
> 
>     * And then the LR1110.
> 
> 
> These are the only ones I've really seen being used. Even the SoCs and modules that can do LoRa are all based on one of the above ones.

Great, thanks a lot for the super useful info!
