### ISSUE TITLE
Strikethrough support in Markdown

### ISSUE THREAD

**Issue by loleg** [TheThingsNetwork/docs#501]
It would be quite useful to be able to use the full range of Markdown in the [community](https://www.thethingsnetwork.org/community/) section of the website (apologies if this bug report should be filed elsewhere, I am assuming it is at least the same engine). Currently the editor shows the strikethrough (`~~some text~~`) formatting in the preview, but does not render it accordingly in the published page.

**Comment by benolayinka** [comment]
@michalborkowski96

**Comment by michalborkowski96** [comment]
@loleg 

I have submitted a PR for this issue. Once it gets accepted, merged and deployed, an ~~S~~ button for strike-through should appear in the editor. Once you see it, please edit and re-save your section, and the strike-through should work.

Realistically, this should be deployed somewhere next week, although that's not a promise.

**Comment by loleg** [comment]
Thanks for the update, looking forward :crossed_fingers:

**Comment by michalborkowski96** [comment]
The change has been deployed

**Comment by loleg** [comment]
Tested and working as promised. Many thanks! Now what else can I strike out...
