### ISSUE TITLE
Describe generated QR codes in more detail

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/docs#505]
#### Summary

would be nice to go into more detail about the QR code generation

#### Why do we need this ?

For better understanding of the required fields, device types for which different types of QR codes should be used and how they should be generated

#### What is already there? What do you see now?

https://www.thethingsindustries.com/docs/devices/generate-qr-code/

#### What is missing? What do you want to see?

Having the content string that is contained in the QR, and what it is decoded to would be helpful
Also mention the minimal required set of fields to make claiming possible

As an example how it is presented in TR005 of LoRa Alliance (section 4.3 - Example QR codes)
https://lora-alliance.org/wp-content/uploads/2020/11/TR005_LoRaWAN_Device_Identification_QR_Codes.pdf

#### How do you propose to document this?

Look into the QR code generation procedure, expand the current doc page

#### Can you do this yourself and submit a Pull Request?

Can assist in collecting information

**Comment by nejraselimovic** [comment]
Closing this as it is in the wrong repository, replacing with https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/853
