### ISSUE TITLE
Rename "refactor" to "v2-preview"

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/docs#54]

**Comment by FokkeZB** [comment]
@htdvisser I thought about `preview` to be better than `refactor`, but does this mean we will rename `staging.thethingsnetwork.org` to `v1-preview.thethingsnetwork.org`? That would make it more logical.

**Comment by htdvisser** [comment]
I'm afraid it's a little too late for that

**Comment by FokkeZB** [comment]
Cant we just redirect staging.ttn to preview-v1.console.ttn and preview.console to preview-v2.console.ttn? It's hard to tell what comes first, staging or preview

**Comment by htdvisser** [comment]
I don't know how much work that will be. @johanstokking, @romeovs and me will discuss the (technical) migration process from staging to the new backend today. I think that spending a lot of time on renaming staging to preview-v1 is not reasonable, but when it can be done quickly it might be worth it.

**Comment by johanstokking** [comment]
Let's keep staging as-is, remove it soon from docs, let it die silently and take it offline in 2017Q1.
