### ISSUE TITLE
Please stop renaming the community network, which is already known by 7 different names at this point.

### ISSUE THREAD

**Issue by HouzuoGuo** [TheThingsNetwork/docs#547]
See also prior issue: https://github.com/TheThingsNetwork/docs/issues/473

#### Summary
The community-run free edition of your network is already known by 6(!) largely interchangeable names, this is incredibly confusing and incredibly harmful for developers and users.

Last I logged into the network console, it's been renamed again for the 7th time to "The Things Stack Sandbox".

Please stop this madness.

**Comment by KrishnaIyer** [comment]
Please use the forum for general comments.

**Comment by HouzuoGuo** [comment]
This is not a general comment, but a legit technical challenge highlighting the shortcomings of documentation. Nowhere in the documentation is there a list of glossaries of many historical and current names of the *newer* version of the things network, the prior issue remains unresolved till this day.

Please get in touch with your branding and marketing colleagues to determine an appropriate course forward. Otherwise, documentation readers - developers and users alike, currently have minimal clue whether any technical documentation page applies to the *newer* version of the things network.
