### ISSUE TITLE
Improvement: Use byte pointers instead of bit shifting?

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#62]
We can get rid of the bit shifting on Arduino by using byte pointers instead. This might be easier for users to understand:

Before:

``` c
byte payload[4];

long lng = 200000L;
payload[0] = (int) ((lng & 0xFF000000) >> 24 );
payload[1] = (int) ((lng & 0x00FF0000) >> 16 );
payload[2] = (int) ((lng & 0x0000FF00) >> 8  );
payload[3] = (int) ((lng & 0X000000FF)       );
```

After:

``` c
byte payload[4];

long lng = 200000L;
byte* bytes = (byte*) &lng;
payload[0] = bytes[3];
payload[1] = bytes[2];
payload[2] = bytes[1];
payload[3] = bytes[0];
```

What do you think @johanstokking?

**Comment by johanstokking** [comment]
The last example is not going to work, I suppose you mean `payload[x]` on the left side.

But yes, we can do this. 

As discussed, we need to explicitly state the length of the type. Instead of `long`, we need `uint32_t` or `int32_t`. Same for `int` and `byte`.

**Comment by FokkeZB** [comment]
Indeed, fixed the above example.

I'll document that users should use explicit length and I have created https://github.com/TheThingsNetwork/arduino-device-lib/issues/103 to do so in the examples.
