### ISSUE TITLE
Clarify gateway connection settings

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/docs#64]
You **must** use DNS. IP addresses may change.

**Comment by FokkeZB** [comment]
Where should we put this? In the Multitech and other future gateway guides? They already use the DNS right? But just as an extra warning?

**Comment by htdvisser** [comment]
Yeah, extra warning. And we should change [this Labs story](https://www.thethingsnetwork.org/labs/story/setting-up-your-own-gateway-and-endpoint-with-microchips-lora-technology-evaluation-kit)

**Comment by FokkeZB** [comment]
I've asked the author why he uses IP there and to change it to hostname if possible.
