### ISSUE TITLE
Import ion icons for use in docs

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/docs#78]
When a doc refers to a button with an icon it should display that same icon. It would be very easy if the docs could import a CSS stylesheet so that you can do something like `<i class="ttn-icon ttn-icon-copy"></i>` in the markdown content.

Currently [a lot](https://github.com/TheThingsIndustries/console/tree/v2-preview/src/components/icons) of the icons used in the console are inline SVG. To keep it DRY these would need to be replaced by an icon font.

**Comment by romeovs** [comment]
These svg icons are svg because they are animated in some way. Most of them are also just a copy-paste from the icon font we use ([ionicons](http://ionicons.com)).

In the console, we just use the CDN version of ion icons.
